### PR TITLE
Register functions

### LINKED ISSUE #11: Register functions as well as components
Sometimes there's the case where your component is simply an initialization step or a cycle loop. There isn't a need to specify all functions that [Component](https://github.com/BotsBurgh/BOTSBURGH-FTC-2022-23/blob/373efe2692b6af3f23d3184ad90bd5068b47db4f/TeamCode/src/main/java/org/firstinspires/ftc/teamcode/api/arch/Component.kt) offers.

I propose 3 functions be created: `registerPre`, `registerCycle`, and `registerPost`. These would be similar to [`register`](https://github.com/BotsBurgh/BOTSBURGH-FTC-2022-23/blob/373efe2692b6af3f23d3184ad90bd5068b47db4f/TeamCode/src/main/java/org/firstinspires/ftc/teamcode/api/arch/Robot.kt#L15-L18), but it would take a function that should be run instead of a component. These functions should also have named arguments for ordering and opmode.

### PR DESCRIPTION
**Pull request by BD103**
Closes #11.

### CODE REVIEW

**Comment by BD103** [comment]
Please review @Vif15 and tell me what you think.

**Review by Vif15 — APPROVED** [review]
looks good

**Review by cadenceforney — APPROVED** [review]
it looks good to me!

**Comment by BD103** [comment]
Thank you @Vif15 and @cadenceforney for reviewing!

**Pull request merged**
